[package]
name = "gome-server-rust"
version = "0.1.0"
authors = ["Matt Silber <cruceo@guardanis.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.25.0"
serde_json = "1.0"